language: node_js
node_js:
  - 'lts/*'

cache:
  yarn: true

script:
  - yarn build

after_success: yarn coverage --file=./coverage/lcov.info && ls -lah

notifications:
  email:
    on_success: never
    on_failure: always
